# Generated by Django 5.0.4 on 2024-04-28 18:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='areas_of_interest',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='organization',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='profile_picture_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
