# Generated by Django 5.0.4 on 2024-04-28 18:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_alter_mentee_areas_of_interest_alter_mentee_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='areas_of_expertise',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='profile_picture_url',
            field=models.CharField(max_length=150),
        ),
    ]
