# Generated by Django 5.0.4 on 2024-04-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_alter_mentor_areas_of_expertise_alter_mentor_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
