# Generated by Django 4.2 on 2024-05-15 13:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0009_alter_mentee_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availableSlots', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='static.mentor')),
            ],
        ),
    ]
