# Generated by Django 4.2 on 2024-05-02 06:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookedSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('profile_picture_url', models.CharField(max_length=200)),
                ('areas_of_interest', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('description', models.TextField()),
                ('role', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('is_experience', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('profile_picture_url', models.CharField(max_length=150)),
                ('areas_of_expertise', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('number_of_likes', models.IntegerField()),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('MentorExperience', models.FloatField()),
                ('designation', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('is_top_rated', models.BooleanField()),
                ('is_experience', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_date', models.DateField()),
                ('from_slot_time', models.TimeField()),
                ('to_slot_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='static.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('ratings', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booked_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='static.bookedsession')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_duration', models.DateTimeField()),
                ('to_duration', models.DateTimeField()),
                ('company', models.TextField()),
                ('role', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('role_type', models.CharField(choices=[('mentor', 'Mentor'), ('mentee', 'Mentee')], max_length=10)),
                ('referenced_id', models.IntegerField()),
                ('menteeRef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='static.mentee')),
                ('mentorRef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='static.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='RequestedSession',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='static.session')),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='static.mentee')),
            ],
        ),
        migrations.AddField(
            model_name='bookedsession',
            name='requested_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='static.requestedsession'),
        ),
    ]
