# Generated by Django 4.2 on 2024-05-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='email_id',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='email_id',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
