# Generated by Django 4.2 on 2024-05-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0002_alter_experience_company_alter_experience_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentor',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
