# Generated by Django 4.2 on 2024-05-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0003_mentee_is_email_verified_mentor_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='is_email_verified',
        ),
    ]
