# Generated by Django 4.2 on 2024-05-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0006_alter_mentee_areas_of_interest_alter_mentee_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='MentorExperience',
            new_name='mentor_experience',
        ),
    ]
