# Generated by Django 4.2 on 2024-05-07 15:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0007_rename_mentorexperience_mentor_mentor_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='session',
            name='count_of_sessions',
            field=models.IntegerField(default=0),
        ),
    ]
