# Generated by Django 4.2 on 2024-05-16 12:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0010_availabesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabesession',
            name='availableSlots',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
    ]
