# Generated by Django 4.2 on 2024-05-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0011_alter_availabesession_availableslots'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('user_type', models.CharField(max_length=100)),
                ('referenceId', models.IntegerField()),
                ('jwt_token', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
