# Generated by Django 4.2 on 2024-06-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0013_userquery_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='to_duration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
