# Generated by Django 5.0.6 on 2024-06-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0014_alter_experience_title_alter_experience_to_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedsession',
            name='hosting_url',
            field=models.TextField(default='hello'),
        ),
        migrations.AddField(
            model_name='bookedsession',
            name='join_url',
            field=models.TextField(default='hello'),
        ),
    ]
