# Generated by Django 5.0.6 on 2024-06-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0015_bookedsession_hosting_url_bookedsession_join_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedsession',
            name='hosting_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bookedsession',
            name='join_url',
            field=models.TextField(),
        ),
    ]
