# Generated by Django 4.2 on 2024-06-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0016_alter_bookedsession_hosting_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='count_of_sessions',
        ),
        migrations.AddField(
            model_name='mentor',
            name='count_of_sessions',
            field=models.IntegerField(default=0),
        ),
    ]
