# Generated by Django 4.2 on 2024-06-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0017_remove_session_count_of_sessions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedsession',
            name='reason',
            field=models.TextField(default='First'),
        ),
    ]
