# Generated by Django 4.2 on 2024-06-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0019_alter_requestedsession_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='mentee',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='mentor',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='mentee_name',
            field=models.TextField(default='Mentee name', max_length=150),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='mentee_profile',
            field=models.TextField(default='Mentee profile', max_length=150),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='mentor_name',
            field=models.TextField(default='Mentor name', max_length=150),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='mentor_profile',
            field=models.TextField(default='Mentor profile', max_length=150),
        ),
    ]
