# Generated by Django 4.2 on 2024-06-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0020_remove_testimonial_mentee_remove_testimonial_mentor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='mentor_organization',
            field=models.TextField(default='Mentor org', max_length=150),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='mentor_role',
            field=models.TextField(default='Mentor role', max_length=150),
        ),
    ]
