# Generated by Django 4.2 on 2024-06-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0021_testimonial_mentor_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='mentee_role',
            field=models.TextField(default='Mentee role', max_length=150),
        ),
    ]
