from django.db import models

class Mentee(models.Model):
    id = models.AutoField(primary_key=True)
    first_name = models.TextField()
    last_name = models.TextField()
    country = models.TextField()
    email_id = models.TextField()
    phone_number = models.TextField()
    password = models.TextField()
    gender = models.TextField()
    date_of_birth = models.DateField()
    city = models.TextField()
    profile_picture_url = models.TextField()
    areas_of_interest = models.ArrayField(models.TextField())
    description = models.TextField()
    role = models.TextField()
    organization = models.TextField()
    is_experience = models.BooleanField()
    created_at = models.DateTimeField(null=False, auto_now_add=True)

class Mentor(models.Model):
    id = models.AutoField(primary_key=True)
    first_name = models.TextField()
    last_name = models.TextField()
    country = models.TextField()
    email_id = models.TextField()
    phone_number = models.TextField()
    password = models.TextField()
    gender = models.TextField()
    date_of_birth = models.DateField()
    city = models.TextField()
    bio = models.TextField()
    profile_picture_url = models.TextField()
    areas_of_expertise = models.ArrayField(models.TextField())
    number_of_likes = models.IntegerField()
    languages = models.ArrayField(models.TextField())
    experience = models.FloatField()
    designation = models.TextField()
    company = models.TextField()
    is_top_rated = models.BooleanField()
    is_experience = models.BooleanField()
    created_at = models.DateTimeField(null=False, auto_now_add=True)

class Experience(models.Model):
    id = models.AutoField(primary_key=True)
    from_duration = models.DateTimeField()
    to_duration = models.DateTimeField()
    company = models.TextField()
    role = models.TextField()
    title = models.TextField()
    description = models.TextField()
    role_type = models.CharField(max_length=10, choices = ['mentor', 'mentee'])
    referenced_id = models.IntegerField()
    mentor = models.ForeignKey(Mentor, on_delete=models.CASCADE, null=True, blank=True)
    mentee = models.ForeignKey(Mentee, on_delete=models.CASCADE, null=True, blank=True)

class Session(models.Model):
    id = models.AutoField(primary_key=True)
    mentor = models.ForeignKey(Mentor, on_delete=models.CASCADE)
    slot_date = models.DateField()
    from_slot_time = models.TimeField()
    to_slot_time = models.TimeField()
    is_booked = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

class RequestedSession(models.Model):
    session = models.OneToOneField(Session, on_delete=models.CASCADE, primary_key=True)
    mentee = models.ForeignKey(Mentee, on_delete=models.CASCADE)
    is_accepted = models.BooleanField(default=False)
    created_at = models.DateTimeField(null=False, auto_now_add=True)

class BookedSession(models.Model):
    id = models.AutoField(primary_key=True)
    requested_session = models.OneToOneField(RequestedSession, on_delete=models.CASCADE)
    is_completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(null=False, auto_now_add=True)

class SessionFeedback(models.Model):
    id = models.AutoField(primary_key=True)
    booked_session = models.OneToOneField(BookedSession, on_delete=models.CASCADE)
    description = models.TextField()
    ratings = models.IntegerField()
    created_at = models.DateTimeField(null=False, auto_now_add=True)
